import type { ToolDef } from '../types.js';

export const testTools: ToolDef[] = [
  { name: 'jest_run', description: 'Run Jest test suite', category: 'test', params: [{ name: 'pattern', type: 'string', description: 'Test file pattern', required: false }, { name: 'watch', type: 'boolean', description: 'Watch mode', required: false }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['jest', 'test', 'unit'] },
  { name: 'vitest_run', description: 'Run Vitest test suite', category: 'test', params: [{ name: 'pattern', type: 'string', description: 'Test file pattern', required: false }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['vitest', 'test', 'unit'] },
  { name: 'pytest_run', description: 'Run Python pytest suite', category: 'test', params: [{ name: 'path', type: 'string', description: 'Test path', required: false }, { name: 'marker', type: 'string', description: 'Marker filter', required: false }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['pytest', 'python', 'test'] },
  { name: 'playwright_test', description: 'Run Playwright e2e tests', category: 'test', params: [{ name: 'spec', type: 'string', description: 'Spec file', required: false }, { name: 'browser', type: 'string', description: 'Browser', required: false, default: 'chromium' }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'slow', tags: ['playwright', 'e2e', 'browser'] },
  { name: 'cypress_run', description: 'Run Cypress e2e tests', category: 'test', params: [{ name: 'spec', type: 'string', description: 'Spec file', required: false }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'slow', tags: ['cypress', 'e2e', 'browser'] },
  { name: 'coverage_report', description: 'Generate test coverage report', category: 'test', params: [{ name: 'format', type: 'string', description: 'Output format', required: false, default: 'text' }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['coverage', 'test', 'report'] },
];

export const lintTools: ToolDef[] = [
  { name: 'eslint_run', description: 'Run ESLint on files', category: 'lint', params: [{ name: 'path', type: 'string', description: 'Path to lint', required: false, default: '.' }, { name: 'fix', type: 'boolean', description: 'Auto-fix', required: false }], returns: 'object', sideEffects: true, requiresPermission: false, estimatedDuration: 'fast', tags: ['eslint', 'lint', 'javascript'] },
  { name: 'prettier_format', description: 'Format code with Prettier', category: 'format', params: [{ name: 'path', type: 'string', description: 'Path to format', required: true }, { name: 'check', type: 'boolean', description: 'Check only', required: false }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'fast', tags: ['prettier', 'format', 'style'] },
  { name: 'ruff_check', description: 'Run Ruff Python linter', category: 'lint', params: [{ name: 'path', type: 'string', description: 'Path to check', required: false, default: '.' }, { name: 'fix', type: 'boolean', description: 'Auto-fix', required: false }], returns: 'object', sideEffects: true, requiresPermission: false, estimatedDuration: 'fast', tags: ['ruff', 'python', 'lint'] },
  { name: 'clippy', description: 'Run Rust clippy linter', category: 'lint', params: [], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['clippy', 'rust', 'lint'] },
  { name: 'shellcheck', description: 'Lint shell scripts', category: 'lint', params: [{ name: 'path', type: 'string', description: 'Script path', required: true }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['shellcheck', 'bash', 'lint'] },
];
