import type { ToolDef } from '../types.js';

export const gitTools: ToolDef[] = [
  { name: 'git_status', description: 'Show working tree status', category: 'git', params: [{ name: 'path', type: 'string', description: 'Repo path', required: false }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['git', 'status', 'vcs'] },
  { name: 'git_diff', description: 'Show staged and unstaged changes', category: 'git', params: [{ name: 'path', type: 'string', description: 'Repo path', required: false }, { name: 'staged', type: 'boolean', description: 'Show staged only', required: false }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['git', 'diff', 'changes'] },
  { name: 'git_log', description: 'Show commit history', category: 'git', params: [{ name: 'path', type: 'string', description: 'Repo path', required: false }, { name: 'limit', type: 'number', description: 'Max entries', required: false, default: 20 }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['git', 'log', 'history'] },
  { name: 'git_add', description: 'Stage files for commit', category: 'git', params: [{ name: 'files', type: 'string[]', description: 'File paths to stage', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['git', 'add', 'stage'] },
  { name: 'git_commit', description: 'Create a commit with message', category: 'git', params: [{ name: 'message', type: 'string', description: 'Commit message', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['git', 'commit'] },
  { name: 'git_push', description: 'Push to remote', category: 'git', params: [{ name: 'remote', type: 'string', description: 'Remote name', required: false, default: 'origin' }, { name: 'branch', type: 'string', description: 'Branch name', required: false }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['git', 'push', 'remote'] },
  { name: 'git_pull', description: 'Pull from remote', category: 'git', params: [{ name: 'remote', type: 'string', description: 'Remote name', required: false, default: 'origin' }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['git', 'pull', 'remote'] },
  { name: 'git_branch', description: 'Create, list, or delete branches', category: 'git', params: [{ name: 'name', type: 'string', description: 'Branch name', required: false }, { name: 'action', type: 'string', description: 'create|list|delete', required: false, default: 'list' }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'instant', tags: ['git', 'branch'] },
  { name: 'git_checkout', description: 'Switch branches or restore files', category: 'git', params: [{ name: 'target', type: 'string', description: 'Branch or file', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['git', 'checkout', 'switch'] },
  { name: 'git_merge', description: 'Merge a branch into current', category: 'git', params: [{ name: 'branch', type: 'string', description: 'Branch to merge', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['git', 'merge'] },
  { name: 'git_stash', description: 'Stash or pop changes', category: 'git', params: [{ name: 'action', type: 'string', description: 'push|pop|list', required: false, default: 'push' }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'instant', tags: ['git', 'stash'] },
  { name: 'git_clone', description: 'Clone a repository', category: 'git', params: [{ name: 'url', type: 'string', description: 'Repo URL', required: true }, { name: 'dest', type: 'string', description: 'Destination path', required: false }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['git', 'clone'] },
  { name: 'git_tag', description: 'Create or list tags', category: 'git', params: [{ name: 'name', type: 'string', description: 'Tag name', required: false }, { name: 'message', type: 'string', description: 'Tag message', required: false }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'instant', tags: ['git', 'tag', 'release'] },
  { name: 'gh_pr_create', description: 'Create a GitHub pull request', category: 'git', params: [{ name: 'title', type: 'string', description: 'PR title', required: true }, { name: 'body', type: 'string', description: 'PR body', required: true }, { name: 'base', type: 'string', description: 'Base branch', required: false }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['github', 'pr', 'pull-request'] },
  { name: 'gh_issue_create', description: 'Create a GitHub issue', category: 'git', params: [{ name: 'title', type: 'string', description: 'Issue title', required: true }, { name: 'body', type: 'string', description: 'Issue body', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['github', 'issue'] },
];
