import type { ToolDef } from '../types.js';

export const deployTools: ToolDef[] = [
  { name: 'vercel_deploy', description: 'Deploy to Vercel', category: 'deploy', params: [{ name: 'prod', type: 'boolean', description: 'Production deploy', required: false }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['vercel', 'deploy', 'hosting'] },
  { name: 'fly_deploy', description: 'Deploy to Fly.io', category: 'deploy', params: [{ name: 'app', type: 'string', description: 'App name', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['fly', 'deploy', 'hosting'] },
  { name: 'railway_deploy', description: 'Deploy to Railway', category: 'deploy', params: [{ name: 'service', type: 'string', description: 'Service name', required: false }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['railway', 'deploy', 'hosting'] },
  { name: 'aws_s3_sync', description: 'Sync files to S3 bucket', category: 'cloud', params: [{ name: 'source', type: 'string', description: 'Source path', required: true }, { name: 'bucket', type: 'string', description: 'S3 bucket URI', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['aws', 's3', 'sync'] },
  { name: 'gcp_deploy', description: 'Deploy to Google Cloud Run', category: 'cloud', params: [{ name: 'image', type: 'string', description: 'Container image', required: true }, { name: 'service', type: 'string', description: 'Service name', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['gcp', 'cloud-run', 'deploy'] },
];

export const dbTools: ToolDef[] = [
  { name: 'sql_query', description: 'Execute a SQL query', category: 'database', params: [{ name: 'query', type: 'string', description: 'SQL query', required: true }, { name: 'connection', type: 'string', description: 'Connection string', required: true }], returns: 'object[]', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['sql', 'database', 'query'] },
  { name: 'redis_get', description: 'Get value from Redis', category: 'database', params: [{ name: 'key', type: 'string', description: 'Redis key', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['redis', 'cache', 'get'] },
  { name: 'redis_set', description: 'Set value in Redis', category: 'database', params: [{ name: 'key', type: 'string', description: 'Redis key', required: true }, { name: 'value', type: 'string', description: 'Value', required: true }, { name: 'ttl', type: 'number', description: 'TTL in seconds', required: false }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['redis', 'cache', 'set'] },
  { name: 'prisma_migrate', description: 'Run Prisma migrations', category: 'database', params: [{ name: 'name', type: 'string', description: 'Migration name', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['prisma', 'migration', 'database'] },
  { name: 'prisma_generate', description: 'Generate Prisma client', category: 'database', params: [], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'fast', tags: ['prisma', 'generate', 'orm'] },
];

export const cryptoTools: ToolDef[] = [
  { name: 'hash_file', description: 'Compute hash of a file', category: 'crypto', params: [{ name: 'path', type: 'string', description: 'File path', required: true }, { name: 'algorithm', type: 'string', description: 'Hash algo', required: false, default: 'sha256' }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['hash', 'sha256', 'checksum'] },
  { name: 'generate_key', description: 'Generate a random secret key', category: 'crypto', params: [{ name: 'length', type: 'number', description: 'Key length bytes', required: false, default: 32 }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['key', 'random', 'secret'] },
  { name: 'encrypt_file', description: 'Encrypt a file with AES', category: 'crypto', params: [{ name: 'path', type: 'string', description: 'File path', required: true }, { name: 'key', type: 'string', description: 'Encryption key', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['encrypt', 'aes', 'security'] },
  { name: 'decrypt_file', description: 'Decrypt an AES encrypted file', category: 'crypto', params: [{ name: 'path', type: 'string', description: 'File path', required: true }, { name: 'key', type: 'string', description: 'Decryption key', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['decrypt', 'aes', 'security'] },
];

export const shellTools: ToolDef[] = [
  { name: 'exec_command', description: 'Execute a shell command', category: 'shell', params: [{ name: 'command', type: 'string', description: 'Shell command', required: true }, { name: 'cwd', type: 'string', description: 'Working directory', required: false }, { name: 'timeout', type: 'number', description: 'Timeout ms', required: false, default: 30000 }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['shell', 'exec', 'command'] },
  { name: 'start_process', description: 'Start a long-running process', category: 'shell', params: [{ name: 'command', type: 'string', description: 'Command to run', required: true }], returns: 'number', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['process', 'start', 'daemon'] },
  { name: 'kill_process', description: 'Kill a running process by PID', category: 'shell', params: [{ name: 'pid', type: 'number', description: 'Process ID', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['process', 'kill', 'stop'] },
  { name: 'env_get', description: 'Get environment variable', category: 'shell', params: [{ name: 'name', type: 'string', description: 'Variable name', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['env', 'environment', 'config'] },
  { name: 'env_set', description: 'Set environment variable', category: 'shell', params: [{ name: 'name', type: 'string', description: 'Variable name', required: true }, { name: 'value', type: 'string', description: 'Value', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['env', 'environment', 'config'] },
];

export const transformTools: ToolDef[] = [
  { name: 'json_parse', description: 'Parse and query JSON', category: 'transform', params: [{ name: 'input', type: 'string', description: 'JSON string or file path', required: true }, { name: 'query', type: 'string', description: 'JQ-style query', required: false }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['json', 'parse', 'jq'] },
  { name: 'yaml_parse', description: 'Parse YAML to object', category: 'transform', params: [{ name: 'input', type: 'string', description: 'YAML string', required: true }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['yaml', 'parse'] },
  { name: 'csv_parse', description: 'Parse CSV to records', category: 'transform', params: [{ name: 'path', type: 'string', description: 'CSV file', required: true }, { name: 'delimiter', type: 'string', description: 'Delimiter', required: false, default: ',' }], returns: 'object[]', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['csv', 'parse', 'data'] },
  { name: 'base64_encode', description: 'Base64 encode string or file', category: 'transform', params: [{ name: 'input', type: 'string', description: 'Input data', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['base64', 'encode'] },
  { name: 'base64_decode', description: 'Base64 decode to string', category: 'transform', params: [{ name: 'input', type: 'string', description: 'Base64 string', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['base64', 'decode'] },
  { name: 'markdown_to_html', description: 'Convert markdown to HTML', category: 'transform', params: [{ name: 'input', type: 'string', description: 'Markdown content', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['markdown', 'html', 'convert'] },
  { name: 'template_render', description: 'Render a template with data', category: 'generate', params: [{ name: 'template', type: 'string', description: 'Template string', required: true }, { name: 'data', type: 'object', description: 'Template data', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['template', 'render', 'generate'] },
  { name: 'code_generate', description: 'Generate code from spec', category: 'generate', params: [{ name: 'spec', type: 'object', description: 'Code spec', required: true }, { name: 'language', type: 'string', description: 'Target language', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['codegen', 'generate', 'scaffold'] },
  { name: 'schema_validate', description: 'Validate data against JSON Schema', category: 'validate', params: [{ name: 'data', type: 'object', description: 'Data to validate', required: true }, { name: 'schema', type: 'object', description: 'JSON Schema', required: true }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['validate', 'schema', 'json'] },
  { name: 'diff_files', description: 'Diff two files or strings', category: 'transform', params: [{ name: 'a', type: 'string', description: 'First input', required: true }, { name: 'b', type: 'string', description: 'Second input', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['diff', 'compare'] },
  { name: 'archive_create', description: 'Create zip/tar archive', category: 'archive', params: [{ name: 'paths', type: 'string[]', description: 'Files to archive', required: true }, { name: 'output', type: 'string', description: 'Output path', required: true }, { name: 'format', type: 'string', description: 'zip|tar|tar.gz', required: false, default: 'zip' }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['archive', 'zip', 'tar'] },
  { name: 'archive_extract', description: 'Extract archive', category: 'archive', params: [{ name: 'path', type: 'string', description: 'Archive path', required: true }, { name: 'dest', type: 'string', description: 'Destination', required: true }], returns: 'string[]', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['archive', 'extract', 'unzip'] },
];

export const monitoringTools: ToolDef[] = [
  { name: 'system_info', description: 'Get system info (OS, CPU, memory)', category: 'monitoring', params: [], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['system', 'info', 'os'] },
  { name: 'disk_usage', description: 'Check disk space usage', category: 'monitoring', params: [{ name: 'path', type: 'string', description: 'Mount point', required: false, default: '/' }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['disk', 'space', 'usage'] },
  { name: 'process_list', description: 'List running processes', category: 'monitoring', params: [{ name: 'filter', type: 'string', description: 'Name filter', required: false }], returns: 'object[]', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['process', 'list', 'ps'] },
  { name: 'port_check', description: 'Check if a port is in use', category: 'monitoring', params: [{ name: 'port', type: 'number', description: 'Port number', required: true }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['port', 'network', 'check'] },
  { name: 'log_tail', description: 'Tail a log file', category: 'monitoring', params: [{ name: 'path', type: 'string', description: 'Log file path', required: true }, { name: 'lines', type: 'number', description: 'Lines to read', required: false, default: 50 }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['log', 'tail', 'monitor'] },
];

export const aiTools: ToolDef[] = [
  { name: 'llm_prompt', description: 'Send prompt to an LLM', category: 'ai', params: [{ name: 'prompt', type: 'string', description: 'User prompt', required: true }, { name: 'model', type: 'string', description: 'Model name', required: false, default: 'claude-sonnet-4-20250514' }, { name: 'maxTokens', type: 'number', description: 'Max tokens', required: false, default: 4096 }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['llm', 'ai', 'prompt'] },
  { name: 'embedding_create', description: 'Create text embeddings', category: 'ai', params: [{ name: 'text', type: 'string', description: 'Input text', required: true }, { name: 'model', type: 'string', description: 'Embedding model', required: false }], returns: 'number[]', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['embedding', 'ai', 'vector'] },
  { name: 'vector_search', description: 'Search vector database', category: 'ai', params: [{ name: 'query', type: 'string', description: 'Search query', required: true }, { name: 'index', type: 'string', description: 'Index name', required: true }, { name: 'topK', type: 'number', description: 'Results count', required: false, default: 10 }], returns: 'object[]', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['vector', 'search', 'pinecone'] },
  { name: 'image_generate', description: 'Generate image from prompt', category: 'media', params: [{ name: 'prompt', type: 'string', description: 'Image description', required: true }, { name: 'size', type: 'string', description: 'Image size', required: false, default: '1024x1024' }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['image', 'generate', 'ai'] },
  { name: 'speech_to_text', description: 'Transcribe audio to text', category: 'media', params: [{ name: 'path', type: 'string', description: 'Audio file', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['transcribe', 'audio', 'stt'] },
  { name: 'text_to_speech', description: 'Convert text to audio', category: 'media', params: [{ name: 'text', type: 'string', description: 'Text to speak', required: true }, { name: 'voice', type: 'string', description: 'Voice ID', required: false }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['tts', 'audio', 'speech'] },
];
