import type { ToolDef } from '../types.js';

export const buildTools: ToolDef[] = [
  { name: 'npm_install', description: 'Install npm dependencies', category: 'build', params: [{ name: 'packages', type: 'string[]', description: 'Package names', required: false }, { name: 'dev', type: 'boolean', description: 'Dev dependency', required: false }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['npm', 'install', 'node'] },
  { name: 'npm_run', description: 'Run an npm script', category: 'build', params: [{ name: 'script', type: 'string', description: 'Script name', required: true }, { name: 'args', type: 'string[]', description: 'Script args', required: false }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'medium', tags: ['npm', 'run', 'script'] },
  { name: 'tsc_build', description: 'Run TypeScript compiler', category: 'build', params: [{ name: 'project', type: 'string', description: 'tsconfig path', required: false }, { name: 'noEmit', type: 'boolean', description: 'Type check only', required: false }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'medium', tags: ['typescript', 'compile', 'build'] },
  { name: 'esbuild_bundle', description: 'Bundle with esbuild', category: 'build', params: [{ name: 'entry', type: 'string', description: 'Entry point', required: true }, { name: 'outfile', type: 'string', description: 'Output file', required: true }, { name: 'format', type: 'string', description: 'esm|cjs|iife', required: false, default: 'esm' }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'fast', tags: ['esbuild', 'bundle', 'build'] },
  { name: 'vite_build', description: 'Build with Vite', category: 'build', params: [{ name: 'mode', type: 'string', description: 'Build mode', required: false, default: 'production' }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'medium', tags: ['vite', 'build', 'frontend'] },
  { name: 'pip_install', description: 'Install Python packages', category: 'build', params: [{ name: 'packages', type: 'string[]', description: 'Package names', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['pip', 'python', 'install'] },
  { name: 'cargo_build', description: 'Build Rust project with cargo', category: 'build', params: [{ name: 'release', type: 'boolean', description: 'Release build', required: false }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'slow', tags: ['cargo', 'rust', 'build'] },
  { name: 'go_build', description: 'Build Go project', category: 'build', params: [{ name: 'output', type: 'string', description: 'Output binary', required: false }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'medium', tags: ['go', 'build', 'compile'] },
  { name: 'make', description: 'Run make with target', category: 'build', params: [{ name: 'target', type: 'string', description: 'Make target', required: false, default: 'all' }, { name: 'args', type: 'string[]', description: 'Make args', required: false }], returns: 'string', sideEffects: true, requiresPermission: false, estimatedDuration: 'medium', tags: ['make', 'build'] },
  { name: 'docker_build', description: 'Build a Docker image', category: 'container', params: [{ name: 'tag', type: 'string', description: 'Image tag', required: true }, { name: 'dockerfile', type: 'string', description: 'Dockerfile path', required: false }, { name: 'context', type: 'string', description: 'Build context', required: false, default: '.' }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['docker', 'build', 'image'] },
  { name: 'docker_run', description: 'Run a Docker container', category: 'container', params: [{ name: 'image', type: 'string', description: 'Image name', required: true }, { name: 'cmd', type: 'string', description: 'Command', required: false }, { name: 'ports', type: 'string[]', description: 'Port mappings', required: false }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['docker', 'run', 'container'] },
  { name: 'docker_compose_up', description: 'Start docker-compose services', category: 'container', params: [{ name: 'file', type: 'string', description: 'Compose file', required: false }, { name: 'detach', type: 'boolean', description: 'Detached mode', required: false, default: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['docker', 'compose', 'services'] },
];
