import type { ToolDef } from '../types.js';

export const networkTools: ToolDef[] = [
  { name: 'http_get', description: 'Fetch content from a URL', category: 'network', params: [{ name: 'url', type: 'string', description: 'URL to fetch', required: true }, { name: 'headers', type: 'object', description: 'HTTP headers', required: false }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['http', 'get', 'fetch'] },
  { name: 'http_post', description: 'POST data to a URL', category: 'network', params: [{ name: 'url', type: 'string', description: 'URL', required: true }, { name: 'body', type: 'object', description: 'Request body', required: true }, { name: 'headers', type: 'object', description: 'HTTP headers', required: false }], returns: 'object', sideEffects: true, requiresPermission: true, estimatedDuration: 'medium', tags: ['http', 'post', 'api'] },
  { name: 'web_search', description: 'Search the web and return results', category: 'search', params: [{ name: 'query', type: 'string', description: 'Search query', required: true }], returns: 'object[]', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['search', 'web', 'google'] },
  { name: 'web_scrape', description: 'Scrape and extract content from a page', category: 'network', params: [{ name: 'url', type: 'string', description: 'Page URL', required: true }, { name: 'selector', type: 'string', description: 'CSS selector', required: false }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['scrape', 'web', 'extract'] },
  { name: 'download_file', description: 'Download a file from URL', category: 'network', params: [{ name: 'url', type: 'string', description: 'File URL', required: true }, { name: 'dest', type: 'string', description: 'Save path', required: true }], returns: 'string', sideEffects: true, requiresPermission: true, estimatedDuration: 'slow', tags: ['download', 'file', 'http'] },
  { name: 'dns_lookup', description: 'DNS lookup for a hostname', category: 'network', params: [{ name: 'hostname', type: 'string', description: 'Hostname', required: true }, { name: 'type', type: 'string', description: 'Record type (A, AAAA, MX, etc)', required: false }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['dns', 'network', 'lookup'] },
  { name: 'ping', description: 'Ping a host', category: 'network', params: [{ name: 'host', type: 'string', description: 'Host to ping', required: true }, { name: 'count', type: 'number', description: 'Ping count', required: false, default: 4 }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['ping', 'network', 'connectivity'] },
  { name: 'traceroute', description: 'Trace route to a host', category: 'network', params: [{ name: 'host', type: 'string', description: 'Target host', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'slow', tags: ['traceroute', 'network', 'diagnostic'] },
  { name: 'whois', description: 'WHOIS lookup for a domain', category: 'network', params: [{ name: 'domain', type: 'string', description: 'Domain name', required: true }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'medium', tags: ['whois', 'domain', 'lookup'] },
  { name: 'ssl_check', description: 'Check SSL certificate details', category: 'network', params: [{ name: 'host', type: 'string', description: 'Hostname', required: true }, { name: 'port', type: 'number', description: 'Port', required: false, default: 443 }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['ssl', 'tls', 'certificate', 'security'] },
];
