import type { ToolDef } from '../types.js';

export const filesystemTools: ToolDef[] = [
  { name: 'read_file', description: 'Read contents of a file', category: 'filesystem', params: [{ name: 'path', type: 'string', description: 'Absolute path', required: true }, { name: 'offset', type: 'number', description: 'Start line', required: false, default: 0 }, { name: 'limit', type: 'number', description: 'Max lines', required: false }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['read', 'file', 'io'] },
  { name: 'write_file', description: 'Write or overwrite a file', category: 'filesystem', params: [{ name: 'path', type: 'string', description: 'Absolute path', required: true }, { name: 'content', type: 'string', description: 'File content', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['write', 'file', 'io'] },
  { name: 'edit_file', description: 'Find and replace in a file', category: 'filesystem', params: [{ name: 'path', type: 'string', description: 'Absolute path', required: true }, { name: 'old_string', type: 'string', description: 'Text to find', required: true }, { name: 'new_string', type: 'string', description: 'Replacement text', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['edit', 'file', 'replace'] },
  { name: 'delete_file', description: 'Delete a file from disk', category: 'filesystem', params: [{ name: 'path', type: 'string', description: 'Absolute path', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['delete', 'file', 'io'] },
  { name: 'copy_file', description: 'Copy a file to a new location', category: 'filesystem', params: [{ name: 'src', type: 'string', description: 'Source path', required: true }, { name: 'dest', type: 'string', description: 'Destination path', required: true }], returns: 'void', sideEffects: true, requiresPermission: false, estimatedDuration: 'instant', tags: ['copy', 'file', 'io'] },
  { name: 'move_file', description: 'Move or rename a file', category: 'filesystem', params: [{ name: 'src', type: 'string', description: 'Source path', required: true }, { name: 'dest', type: 'string', description: 'Destination path', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'instant', tags: ['move', 'rename', 'file'] },
  { name: 'list_directory', description: 'List files and directories', category: 'filesystem', params: [{ name: 'path', type: 'string', description: 'Directory path', required: true }, { name: 'depth', type: 'number', description: 'Recursion depth', required: false, default: 2 }], returns: 'string[]', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['list', 'directory', 'ls'] },
  { name: 'create_directory', description: 'Create a directory recursively', category: 'filesystem', params: [{ name: 'path', type: 'string', description: 'Directory path', required: true }], returns: 'void', sideEffects: true, requiresPermission: false, estimatedDuration: 'instant', tags: ['mkdir', 'directory', 'create'] },
  { name: 'glob_search', description: 'Find files by glob pattern', category: 'filesystem', params: [{ name: 'pattern', type: 'string', description: 'Glob pattern', required: true }, { name: 'path', type: 'string', description: 'Root directory', required: false }], returns: 'string[]', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['glob', 'search', 'find'] },
  { name: 'grep_search', description: 'Search file contents with regex', category: 'filesystem', params: [{ name: 'pattern', type: 'string', description: 'Regex pattern', required: true }, { name: 'path', type: 'string', description: 'Root directory', required: false }, { name: 'glob', type: 'string', description: 'File filter', required: false }], returns: 'string[]', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['grep', 'search', 'regex'] },
  { name: 'file_info', description: 'Get file metadata (size, dates, permissions)', category: 'filesystem', params: [{ name: 'path', type: 'string', description: 'File path', required: true }], returns: 'object', sideEffects: false, requiresPermission: false, estimatedDuration: 'instant', tags: ['stat', 'metadata', 'info'] },
  { name: 'watch_files', description: 'Watch directory for file changes', category: 'filesystem', params: [{ name: 'path', type: 'string', description: 'Directory to watch', required: true }, { name: 'pattern', type: 'string', description: 'File filter', required: false }], returns: 'stream', sideEffects: false, requiresPermission: false, estimatedDuration: 'slow', tags: ['watch', 'filesystem', 'events'] },
  { name: 'read_pdf', description: 'Extract text from a PDF file', category: 'pdf', params: [{ name: 'path', type: 'string', description: 'PDF file path', required: true }, { name: 'pages', type: 'string', description: 'Page range', required: false }], returns: 'string', sideEffects: false, requiresPermission: false, estimatedDuration: 'fast', tags: ['pdf', 'read', 'extract'] },
  { name: 'write_pdf', description: 'Create a PDF from markdown content', category: 'pdf', params: [{ name: 'path', type: 'string', description: 'Output path', required: true }, { name: 'content', type: 'string', description: 'Markdown content', required: true }], returns: 'void', sideEffects: true, requiresPermission: true, estimatedDuration: 'fast', tags: ['pdf', 'write', 'create'] },
];
